services:
  counter:
    build: .
    image: ttl.sh/dte/simple-compose/counter
    ports:
      - ${PORT:-80}:80
    depends_on:
      - redis
    environment:
      REDIS: redis
  redis:
    image: redis:8
    volumes:
      - redis-data:/data

volumes:
  redis-data:
